import Head from 'next/head'
import React from 'react'
import Nav from '../components/Nav'

function contact() {
  return (
    <div>
    <Head>
      <title>Ticktok Royal | Contact</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Nav/>
    <div className='bg-indigo-500 p-10'>
      <h1 className='text-2xl text-white'>Who are we</h1>
      <p className='text-white'>We are the people which provides you followers and likes to ypur tiktok acount</p>
    </div>
    </div>   
  )
}

export default contact